app:
  jwt:
    access: 31536000000
    refresh: 86400000
    otp: 300000
    secret: secret
  symmetric:
    secret: secret
    salt: salt

spring:
  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    master:
      jdbcUrl: ${SPRING_DATASOURCE_MASTER_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driverClassName-class-name: org.postgresql.Driver
    slave:
      jdbcUrl: ${SPRING_DATASOURCE_SLAVE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driverClassName-class-name: org.postgresql.Driver
  devtools:
    add-properties: false

logging:
  level:
    org:
      springframework:
        core:
          env=DEBUG: